config/routes.rb
Rails.application.routes.draw do

  resources :referreds
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :insurances

  devise_for :users do
 end
 
  resources :accounts do
    collection do
     get 'search'
    end
    
  resources :notes, except: [:show, :index]
end

resources :programs

   get 'pages/index'
   get "pages/map"

  root 'pages#index'

end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
    has_many :Accounts
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @insurances = Insurance.all
    respond_with(@insurances)
  end

  def show
    respond_with(@insurance)
  end

  def new
    @insurance = Insurance.new
    respond_with(@insurance)
  end

  def edit
  end

  def create
    @insurance = Insurance.new(insurance_params)
    @insurance.save
    respond_with(@insurance)
  end

  def update
    @insurance.update(insurance_params)
    respond_with(@insurance)
  end

  def destroy
    @insurance.destroy
    respond_with(@insurance)
  end

  private
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    def insurance_params
      params.require(:insurance).permit(:name)
    end
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_form.html.erb
<%= form_for @insurance do |f| %>

<div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/insurances/edit.html.erb
<h1>Editing insurance</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/index.html.erb
<h1>Listing insurances</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurances.each do |insurance| %>
      <tr>
        <td><%= insurance.name %></td>
        <td><%= link_to 'Show', insurance %></td>
        <td><%= link_to 'Edit', edit_insurance_path(insurance) %></td>
        <td><%= link_to 'Destroy', insurance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurance', new_insurance_path %>

app/views/insurances/new.html.erb
<h1>New insurance</h1>

<%= render 'form' %>

<%= link_to 'Back', insurances_path %>

app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insurance.name %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>