config/routes.rb
Rails.application.routes.draw do

  resources :referreds
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :insurances

  devise_for :users do
 end
 
  resources :accounts do
    collection do
     get 'search'
    end
    
  resources :notes, except: [:show, :index]
end

resources :programs

   get 'pages/index'
   get "pages/map"

  root 'pages#index'

end

app/models/referred.rb
class Referred < ActiveRecord::Base
    has_many :accounts
end

app/controllers/referreds_controller.rb
class ReferredsController < InheritedResources::Base

  private

    def referred_params
      params.require(:referred).permit(:name)
    end
end

app/helpers/referreds_helper.rb
module ReferredsHelper
end

app/views/referreds/_form.html.erb
<%= semantic_form_for @referred do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/referreds/edit.html.erb
<h1>Editing Referred</h1>

<%= render 'form' %>

<%= link_to 'Show', @referred %> |
<%= link_to 'Back', referreds_path %>

app/views/referreds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Referreds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referreds.each do |referred| %>
      <tr>
        <td><%= referred.name %></td>
        <td><%= link_to 'Show', referred %></td>
        <td><%= link_to 'Edit', edit_referred_path(referred) %></td>
        <td><%= link_to 'Destroy', referred, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referred', new_referred_path %>

app/views/referreds/new.html.erb
<h1>New Referred</h1>

<%= render 'form' %>

<%= link_to 'Back', referreds_path %>

app/views/referreds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @referred.name %>
</p>

<%= link_to 'Edit', edit_referred_path(@referred) %> |
<%= link_to 'Back', referreds_path %>