config/routes.rb
Rails.application.routes.draw do

  resources :referreds
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :insurances

  devise_for :users do
 end
 
  resources :accounts do
    collection do
     get 'search'
    end
    
  resources :notes, except: [:show, :index]
end

resources :programs

   get 'pages/index'
   get "pages/map"

  root 'pages#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
    
    searchkick
    
    
    belongs_to :program
    belongs_to :insurance
    has_many :notes
    belongs_to :referred
    
    #Refactoring with the Null Object Pattern
    def referred
        super || Referred.new
    end
    #
    
    
    validates :first_name, :last_name, :address, :phone, presence: true
    validates :phone, format: { with: /\A\d{3} \d{3}-\d{4}\z/,
    message: "must be in the format 123 456-7890" }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def search
  if params[:search].present?
    @account = Account.search(params[:search])
  else
    @account = Account.all
  end
  end

  def index
    @account = Account.uniq.order("created_at DESC").page(params[:page]).per(10)
    @accounts_count = Account.uniq.count
  end


  def show
    @notes = Note.where(account_id: @account.id) #Where a note belong to the current account
  end

  def new
    @account = Account.new
    respond_with(@account)
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.save
    respond_with(@account)
  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:first_name, :last_name, :return_client, :program_id, :insurance_id, :address, :phone, :referred_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation" class= "alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@account.errors.count, "error") %> prohibited this review from being saved:</h4>
      
      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="well well-sm">
  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.label :return_client, "Returing Client:" %><br>
    <%= f.check_box :return_client %> "Check Box For Yes"
    </div>
    <div class="form-group">
    <%= f.label :program, "Program:" %><br>
    <%= f.collection_select :program_id, Program.all, :id, :name, {prompt: "Choose a Program"}, {class: "btn btn-default dropdown-toggle"} %>
  </div>
  <div class="form-group">
   <%= f.label :insurance, "Insurance:" %><br>
    <%= f.collection_select :insurance_id, Insurance.all, :id, :name, {prompt: "Choose an Insurance"}, {class: "btn btn-default dropdown-toggle"} %>
  </div>
  <div class="form-group">
   <%= f.label :referred, "Reason:" %><br>
    <%= f.collection_select :referred_id, Referred.all, :id, :name, {prompt: "Choose Reason"}, {class: "btn btn-default dropdown-toggle"} %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br> example: 123 Anystreet, New Haven, CT 06515
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "203 000-0000" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>


<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account, class: "btn btn-link" %> |
<%= link_to 'Back', accounts_path, class: "btn btn-link" %>

app/views/accounts/index.html.erb
 <div class="row">
<div class="col-md-8">
    <h2>Client Listing</h2>
    <%= link_to ' Add Client', new_account_path, class: "fa fa-plus-square" %>
    <div class="well ">
<table class="table table-hover table-condensed">
    </div>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
       <% @account.each do |account| %>
      <tr class="info">
        
        <td><%= account.first_name %></td>
        <td><%= account.last_name %></td>
        <td><%= account.address %></td>
        <td><%= account.phone %></td>
        <td>
<%if account.program%>
   <%=account.program.name%>
<%else%>
   Program doesn't exist
<%end%>
</td>
        <td><%= link_to ' Show', account, class: 'fa fa-eye', 'data-toggle': 'tooltip', 'data-placement':'top', title: 'Show Client Account' %></td>
        <td><%= link_to ' Edit', edit_account_path(account), class: "fa fa-pencil-square-o", 'data-toggle': 'tooltip', 'data-placement':'top', title: 'Edit Client Account'  %></td>
        <% if user_signed_in? && current_user.admin? %>
        <td><%= link_to ' Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash", 'data-toggle': 'tooltip', 'data-placement':'top', title: 'Delete Client Account' %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @account %>
</div>
</div>

<div class="col-md-4">
    <br>
    <div align="center">
        <h2>App Info</h2>
        <div class="well well-sm">
    <b>Current Client Count</b>
    <%= @accounts_count %>
  </div>
</div>
</div>
</div>
</div>

app/views/accounts/new.html.erb
<h2>New account</h2>

<%= render 'form' %>

<%= link_to 'Back', accounts_path, class: "btn btn-link" %>

app/views/accounts/search.html.erb
<h1>Listing Client</h1>
<table class="table table-hover table-condensed">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account.each do |account| %>
      <tr>
        <td><%= account.first_name %></td>
        <td><%= account.last_name %></td>
        <td><%= account.address %></td>
        <td><%= account.phone %></td>
        <td>
<%if account.program%>
   <%=account.program.name%>
<%else%>
   Program doesn't exist
<%end%>
</td>
        <td><%= link_to 'Show Client', account, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit Client', edit_account_path(account), class: "btn btn-link" %></td>
        <% if user_signed_in? && current_user.admin? %>
        <td><%= link_to 'Destroy Client', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</table>

<br>
<%= paginate @account %>
<br>
<%= link_to 'Add Client', new_account_path %>

app/views/accounts/show.html.erb
<div class="container">
    
<div class="row">
  
  <div class="col-md-3">
    <div class="well ">
<p>
     <strong>First name:</strong>
  <%= @account.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @account.last_name %>
</p>

<p>
  <strong>Returing Client?:</strong>
  <%= @account.return_client ? 'Yes' : 'No'  %>
</p>
<p>
  <strong>Program:</strong>
  <%= @account.program.name %>
</p>

<p>
  <strong>Insurance:</strong>
  <%= @account.insurance.name %>
</p>

<p>
  <strong>Referred To:</strong>
  <%= @account.referred.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @account.phone %>
</p>

<p>
<strong>Created:</strong> 
<%= @account.created_at.strftime ("%-b-%-d-%y") %>
</p>
</div>

    <%= link_to "Write a note", new_account_note_path(@account), class: "btn btn-primary" %>

    <br>
    <br>
  </div>

  
  <div class="col-md-9">
    <% if @notes.blank? %>
      <h3>No notes yet. Be the first to write one!</h3>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>

        <tbody>
          <% @notes.each do |note| %>
            <tr>
              <td>
                <h4>
                <%= "#{note.user.first_name.capitalize} #{note.user.last_name.capitalize[0]}" %>
                </h4>
                <h5><%= note.created_at.strftime("%-m/%-d/%y") %></h5>
              </td>

              <td>
                <p><%= h(note.comment).gsub(/\n/, '<br/>').html_safe %></p>
                
                <% if user_signed_in? %>
                   <% if (current_user.admin?) %>
                    <%= link_to "Edit Note", edit_account_note_path(@account, note) %>   |
                    <%= link_to "Delete Note", account_note_path(@account, note), method: :delete %>
                    <% else %>
                    <% if (note.user == current_user) %> 
                    <%= link_to "Edit Client", edit_account_note_path(@account, note) %>
                  <% end %>
                <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_account_path(@account), class: "btn btn-link" %> |
<%= link_to 'Back', accounts_path, class: "btn btn-link" %>